---
# handlers file for web_server

# This will restart the service if there are any changes in web page

- name: "Restart HTTPD"
  service:
    name: "{{ httpd_service }}"  # Use variable for service name
    state: restarted
