---
# handlers file for web_server

# This will restart the service if there are any changes in web page

- name: "Restart HAProxy"
  service:
    name: "{{ haproxy_service }}"  # Use variable for service name
    state: restarted
